# Generated by Django 4.2.7 on 2023-12-07 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='matches',
            name='room_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='matches',
            name='draw',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='matches',
            name='loser',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='matches',
            name='player1',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='matches',
            name='player2',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='matches',
            name='winner',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
