# Generated by Django 4.2.7 on 2024-01-01 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_matches_room_name_alter_matches_draw_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='matches',
            name='finished',
            field=models.BooleanField(default=False),
        ),
    ]
