# Generated by Django 4.2.7 on 2024-01-04 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_matches_finished'),
    ]

    operations = [
        migrations.AddField(
            model_name='matches',
            name='seconds',
            field=models.IntegerField(null=True),
        ),
    ]
